### ISSUE TITLE
Error with BuildGeneStatList

### ISSUE THREAD

**Issue by keshav12397** [BaderLab/AgingMouseBrainCCInx#1]
Hi!

Really amazing package and paper, was great to read and I'm excited to try applying it to some RNA-seq data I have. When trying to build a GeneStatList from a SingleCellExperiment object I keep getting the error

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'RowNNZ' for signature '"numeric"'

Any advice would be appreciated, thank you!

**Comment by innesbre** [comment]
I suspect this is because you have a cluster containing one cell.  Check this by `table(cl)` and seeing if one of the levels contains a single entry.  Is that expected?

**Comment by keshav12397** [comment]
Hi Brendan,

Thanks for getting back to me and thanks for the suggestion that fixed it. I am able to build the GeneStatList normally, however now when trying to actually BuildCCInx I continue to get an error 

> Less than 20 genes from GeneStatList were detected in the CCInx database.
  Please ensure that you've set the Species argument correctly.
  Rownames of each entry in GeneStatList must be official gene symbols.

I've tried changing the capitalization of the genes and stuff but still get the same error. I have the gene names, EntrezIDs, and EnsemblGeneIDs for these, is there a praticular database you used for the gene names that I can convert the EntrezIDs into? All of this is in mouse by the way.

**Comment by innesbre** [comment]
Ensure you've set `BuildCCInx(...,Species="mmusculus")` if your input data is MGI gene symbols.  

You can load the database into your R session directly by running `load(system.file("LigRecDB_RData/BaderCCIeditedbyBI_mouse.RData",package="CCInx"))`, then checking that your gene names are in the `geneInfo$mgi_symbol` column.  

If not, try mapping your EntrezIDs to gene symbols using:
```
require(org.Mm.eg.db) # install this with BiocManager::install("org.Mm.eg.db")
your_gene_symbols <- mapIds(org.Mm.eg.db,
                            keys=your_entrezid,
                            column="SYMBOL",
                            keytype="ENTREZID")
```

**Comment by keshav12397** [comment]
So I checked against geneInfo$mgi_symbol and there are plenty of genes in my list that are part of the database. When looking at the values in the generated GeneStatList, I notice the detect rate for all genes is =1, and the MeanDetectGeneExpr is equal to the MeanNormGeneExpr. I was wondering if the program would have difficulties weighing these nodes because the cell types are too similar. This is actually RiboTag RNA-seq data, so not true SingleCell-Seq but I thought I might be able to modify your package a little to use for the RiboTag data.

**Comment by innesbre** [comment]
Yes, in theory that should work.  I'm not sure what's breaking things, so do you mind sending me a subset of your data and I can try running it through to debug it?   Preferably the subset will include more than 20 genes in the geneInfo$mgi_symbol list, and more than one sample from at least two clusters.  You can subset SingleCellExperiment objects using the standard Robject[rows,columns] notation.  Please upload the file to my dropbox at https://www.dropbox.com/request/B5qDwUoKtbRvZGitpkhB
