### ISSUE TITLE
Any code to transfer as Seurat object

### ISSUE THREAD

**Issue by kasumaz** [BaderLab/AgingMouseBrainCCInx#2]
Hi, 
I have been looking at these nice datasets. I have some other datasets from 10X V2 platform and I wanted to merge them all into one Seurat object that I have been working on already. I have been trying to use the datasets as raw files from GEO but this has been tricky so far. I am wondering, by any chance someone has a Seurat object already or any code written that I can use to merge with existing datasets on Seurat? I am most interested in the oligodendroglial lineage cells (oligodendrocytes and OPCs) in young versus ageing in case there is a way to get a reduced datasets. Any help would be very much appreciated. 
Thanks a lot.

**Comment by innesbre** [comment]
Hi!
If you download the following to its own folder: https://www.dropbox.com/sh/hnrhunbaawvggkt/AACsR-kUY5OC_J2YRStkjnPWa?dl=0
Then you should be able to view the data interactively from your R session in scClustViz with the following code:
```
library(scClustViz)
runShiny("path/to/file/AllCellTypes.RData",
         annotationDB="org.Hs.eg.db",
         rownameKeytype="SYMBOL",
         imageFileType="png")
```
If you close the Shiny app window and return to your R session, you'll see that the .RData file loaded two objects, one of which is the list of scClustViz objects, and **the other is the Seurat object**.
Hope that helps!
